# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 615cc2812abe21fe788e83467926660c54180a7ad69be9d1224f4b77e22c13cec7bbe216442b43dc7885a95dcf0550c3cc487b990143338f57abe5e071253abe

test:
  secret_key_base: 6af025b60f866a900905faa4590fd70c848c54611ea0efc51ddef96d0a05d789cba5fed0ffd3f38401d44c116ee992f0a7ad8b9ded9252941a0712f3ac5b5691

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
